server:
  port: 9000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://wook2-rds.c7vimhuuowv7.ap-northeast-2.rds.amazonaws.com/Airbnb?autoReconnect=true
    username:  admin
    password: ENC(JitoXwRvMaJMYiZYHuHaXnmFQAuOqvGx)
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
