server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      force: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://wook2-rds.c7vimhuuowv7.ap-northeast-2.rds.amazonaws.com/Airbnb?autoReconnect=true
    username:  admin
    password: ENC(JitoXwRvMaJMYiZYHuHaXnmFQAuOqvGx)
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  security:
    user:
      name: user
      password: test
    oauth2:
      client:
        registration:
          kakao:
            client-id: 40497aa481ce3faa7ef3251506a95bf5
            redirect-uri: http://localhost:9000/oauth/kakao # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

logging:
  config:
  classpath: log4j2.xml
